### ISSUE TITLE
broccoli-taco serve throws TypeError: Arguments to path.join must be strings

### ISSUE THREAD

**Issue by JimmiLee** [moudy/broccoli-taco#23]
I'm trying out the broccoli-taco, but I'm getting an error when running `broccoli-taco serve`. I'm using **node v0.12.2**, but when I run broccoli-taco serve it throws a TypeError at me - this is the output:

```
Serving on http://localhost:4200

Built with error:
TypeError: Arguments to path.join must be strings
    at Object.posix.join (path.js:488:13)
    at Fingerprint.getDestFilePath (/home/jimmi/Sites/broccoli-taco-demo/node_modules/broccoli-fingerprint/index.js:43:23)
    at Fingerprint.Filter.canProcessFile (/home/jimmi/Sites/broccoli-taco-demo/node_modules/broccoli-filter/index.js:58:15)
    at /home/jimmi/Sites/broccoli-taco-demo/node_modules/broccoli-filter/index.js:42:18
    at /home/jimmi/Sites/broccoli-taco-demo/node_modules/promise-map-series/index.js:11:14
    at lib$rsvp$$internal$$tryCatch (/home/jimmi/Sites/broccoli-taco-demo/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/home/jimmi/Sites/broccoli-taco-demo/node_modules/rsvp/dist/rsvp.js:505:17)
    at /home/jimmi/Sites/broccoli-taco-demo/node_modules/rsvp/dist/rsvp.js:1001:13
    at lib$rsvp$asap$$flush (/home/jimmi/Sites/broccoli-taco-demo/node_modules/rsvp/dist/rsvp.js:1198:9)
    at process._tickCallback (node.js:355:11)
```

I sincerely hope someone can give me an idea of the problem I'm facing here...

**Comment by juan-manuel-alberro** [comment]
I´ve the same issue @JimmiLee, try this in `node_modules/broccoli-fingerprint/index.js` line 43

`var filepath = path.join(this.inputTree.outputPath, filename);`

**Comment by givanse** [comment]
You can fix it by locking `broccoli-merge-trees` to version `0.2.1`.

```
// lock broccoli-merge-trees to 0.2.1
rm -rf tmp
npm install
broccoli-taco build dist
```
